#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define ALPHAOS_TOTAL_INTERRUPTS 512

// 100MB heap size
#define ALPHAOS_HEAP_SIZE_BYTES 104857600
#define ALPHAOS_HEAP_BLOCK_SIZE 4096
#define ALPHAOS_HEAP_ADDRESS 0x01000000
#define ALPHAOS_HEAP_TABLE_ADDRESS 0x00007E00

#define ALPHAOS_SECTOR_SIZE 512

#define ALPHAOS_MAX_FILESYSTEMS 12
#define ALPHAOS_MAX_FILEDESCRIPTORS 512

#define ALPHAOS_MAX_PATH_LENGTH 108

#define ALPHAOS_TOTAL_GDT_SEGMENTS 6

#define ALPHAOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define ALPHAOS_USER_PROGRAM_STACK_SIZE 1024 * 16
#define ALPHAOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define ALPHAOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END ALPHAOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - ALPHAOS_USER_PROGRAM_STACK_SIZE

#define ALPHAOS_MAX_PROGRAM_ALLOCATIONS 1024
#define ALPHAOS_MAX_PROCESSES 12

#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1B

#define ALPHAOS_MAX_ISR80H_COMMANDS 1024

#define ALPHAOS_KEYBOARD_BUFFER_SIZE 1024

#endif // CONFIG_H