all:
	$(MAKE) -C stdlib all
	$(MAKE) -C blank all

clean:
	$(MAKE) -C stdlib clean
	$(MAKE) -C blank clean

fclean:
	$(MAKE) -C stdlib fclean
	$(MAKE) -C blank fclean

re:
	$(MAKE) -C stdlib re
	$(MAKE) -C blank re
