all:
	$(MAKE) -C stdlib all
	$(MAKE) -C blank all
	$(MAKE) -C shell all

clean:
	$(MAKE) -C stdlib clean
	$(MAKE) -C blank clean
	$(MAKE) -C shell clean

fclean:
	$(MAKE) -C stdlib fclean
	$(MAKE) -C blank fclean
	$(MAKE) -C shell fclean

re:
	$(MAKE) -C stdlib re
	$(MAKE) -C blank re
	$(MAKE) -C shell re
